version: "3.3"
services:
    site:
        build: .
        volumes:
         - ./assets:/var/www/assets
        restart: always
        expose:
         - "80"
        networks:
         - web
         - default
        labels:
         - "traefik.backend=jasmine-site"
         - "traefik.docker.network=web"
         - "traefik.basic.frontend.rule=Host:happybdayjasmine2018.com"
         - "traefik.enable=true"
         - "traefik.basic.port=80"

networks:
    web:
        external: true
